require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuestionsetsController do

  # This should return the minimal set of attributes required to create a valid
  # Questionset. As you add validations to Questionset, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuestionsetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all questionsets as @questionsets" do
      questionset = Questionset.create! valid_attributes
      get :index, {}, valid_session
      assigns(:questionsets).should eq([questionset])
    end
  end

  describe "GET show" do
    it "assigns the requested questionset as @questionset" do
      questionset = Questionset.create! valid_attributes
      get :show, {:id => questionset.to_param}, valid_session
      assigns(:questionset).should eq(questionset)
    end
  end

  describe "GET new" do
    it "assigns a new questionset as @questionset" do
      get :new, {}, valid_session
      assigns(:questionset).should be_a_new(Questionset)
    end
  end

  describe "GET edit" do
    it "assigns the requested questionset as @questionset" do
      questionset = Questionset.create! valid_attributes
      get :edit, {:id => questionset.to_param}, valid_session
      assigns(:questionset).should eq(questionset)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Questionset" do
        expect {
          post :create, {:questionset => valid_attributes}, valid_session
        }.to change(Questionset, :count).by(1)
      end

      it "assigns a newly created questionset as @questionset" do
        post :create, {:questionset => valid_attributes}, valid_session
        assigns(:questionset).should be_a(Questionset)
        assigns(:questionset).should be_persisted
      end

      it "redirects to the created questionset" do
        post :create, {:questionset => valid_attributes}, valid_session
        response.should redirect_to(Questionset.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved questionset as @questionset" do
        # Trigger the behavior that occurs when invalid params are submitted
        Questionset.any_instance.stub(:save).and_return(false)
        post :create, {:questionset => { "title" => "invalid value" }}, valid_session
        assigns(:questionset).should be_a_new(Questionset)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Questionset.any_instance.stub(:save).and_return(false)
        post :create, {:questionset => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested questionset" do
        questionset = Questionset.create! valid_attributes
        # Assuming there are no other questionsets in the database, this
        # specifies that the Questionset created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Questionset.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => questionset.to_param, :questionset => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested questionset as @questionset" do
        questionset = Questionset.create! valid_attributes
        put :update, {:id => questionset.to_param, :questionset => valid_attributes}, valid_session
        assigns(:questionset).should eq(questionset)
      end

      it "redirects to the questionset" do
        questionset = Questionset.create! valid_attributes
        put :update, {:id => questionset.to_param, :questionset => valid_attributes}, valid_session
        response.should redirect_to(questionset)
      end
    end

    describe "with invalid params" do
      it "assigns the questionset as @questionset" do
        questionset = Questionset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Questionset.any_instance.stub(:save).and_return(false)
        put :update, {:id => questionset.to_param, :questionset => { "title" => "invalid value" }}, valid_session
        assigns(:questionset).should eq(questionset)
      end

      it "re-renders the 'edit' template" do
        questionset = Questionset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Questionset.any_instance.stub(:save).and_return(false)
        put :update, {:id => questionset.to_param, :questionset => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested questionset" do
      questionset = Questionset.create! valid_attributes
      expect {
        delete :destroy, {:id => questionset.to_param}, valid_session
      }.to change(Questionset, :count).by(-1)
    end

    it "redirects to the questionsets list" do
      questionset = Questionset.create! valid_attributes
      delete :destroy, {:id => questionset.to_param}, valid_session
      response.should redirect_to(questionsets_url)
    end
  end

end
