require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SetcompilationsController do

  # This should return the minimal set of attributes required to create a valid
  # Setcompilation. As you add validations to Setcompilation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SetcompilationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all setcompilations as @setcompilations" do
      setcompilation = Setcompilation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:setcompilations).should eq([setcompilation])
    end
  end

  describe "GET show" do
    it "assigns the requested setcompilation as @setcompilation" do
      setcompilation = Setcompilation.create! valid_attributes
      get :show, {:id => setcompilation.to_param}, valid_session
      assigns(:setcompilation).should eq(setcompilation)
    end
  end

  describe "GET new" do
    it "assigns a new setcompilation as @setcompilation" do
      get :new, {}, valid_session
      assigns(:setcompilation).should be_a_new(Setcompilation)
    end
  end

  describe "GET edit" do
    it "assigns the requested setcompilation as @setcompilation" do
      setcompilation = Setcompilation.create! valid_attributes
      get :edit, {:id => setcompilation.to_param}, valid_session
      assigns(:setcompilation).should eq(setcompilation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Setcompilation" do
        expect {
          post :create, {:setcompilation => valid_attributes}, valid_session
        }.to change(Setcompilation, :count).by(1)
      end

      it "assigns a newly created setcompilation as @setcompilation" do
        post :create, {:setcompilation => valid_attributes}, valid_session
        assigns(:setcompilation).should be_a(Setcompilation)
        assigns(:setcompilation).should be_persisted
      end

      it "redirects to the created setcompilation" do
        post :create, {:setcompilation => valid_attributes}, valid_session
        response.should redirect_to(Setcompilation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved setcompilation as @setcompilation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Setcompilation.any_instance.stub(:save).and_return(false)
        post :create, {:setcompilation => { "name" => "invalid value" }}, valid_session
        assigns(:setcompilation).should be_a_new(Setcompilation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Setcompilation.any_instance.stub(:save).and_return(false)
        post :create, {:setcompilation => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested setcompilation" do
        setcompilation = Setcompilation.create! valid_attributes
        # Assuming there are no other setcompilations in the database, this
        # specifies that the Setcompilation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Setcompilation.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => setcompilation.to_param, :setcompilation => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested setcompilation as @setcompilation" do
        setcompilation = Setcompilation.create! valid_attributes
        put :update, {:id => setcompilation.to_param, :setcompilation => valid_attributes}, valid_session
        assigns(:setcompilation).should eq(setcompilation)
      end

      it "redirects to the setcompilation" do
        setcompilation = Setcompilation.create! valid_attributes
        put :update, {:id => setcompilation.to_param, :setcompilation => valid_attributes}, valid_session
        response.should redirect_to(setcompilation)
      end
    end

    describe "with invalid params" do
      it "assigns the setcompilation as @setcompilation" do
        setcompilation = Setcompilation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Setcompilation.any_instance.stub(:save).and_return(false)
        put :update, {:id => setcompilation.to_param, :setcompilation => { "name" => "invalid value" }}, valid_session
        assigns(:setcompilation).should eq(setcompilation)
      end

      it "re-renders the 'edit' template" do
        setcompilation = Setcompilation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Setcompilation.any_instance.stub(:save).and_return(false)
        put :update, {:id => setcompilation.to_param, :setcompilation => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested setcompilation" do
      setcompilation = Setcompilation.create! valid_attributes
      expect {
        delete :destroy, {:id => setcompilation.to_param}, valid_session
      }.to change(Setcompilation, :count).by(-1)
    end

    it "redirects to the setcompilations list" do
      setcompilation = Setcompilation.create! valid_attributes
      delete :destroy, {:id => setcompilation.to_param}, valid_session
      response.should redirect_to(setcompilations_url)
    end
  end

end
